import {
    BsArrowCounterclockwise,
    BsCalendarDate,
    BsChevronDown,
    BsChevronUp,
    BsClock,
    BsFillPauseFill,
    BsFillPencilFill,
    BsFillPersonFill,
    BsFillPlayFill,
    BsFillStopCircleFill,
    BsFillTrash2Fill,
    BsFillVolumeUpFill,
    BsGearFill,
    BsPlusLg,
} from 'react-icons/bs'

export const Icons = {
    Pause: BsFillPauseFill,
    Play: BsFillPlayFill,
    Calendar: BsCalendarDate,
    Pomodoro: BsClock,
    Settings: BsGearFill,
    Profile: BsFillPersonFill,
    Edit: BsFillPencilFill,
    Delete: BsFillTrash2Fill,
    Plus: BsPlusLg,
    Down: BsChevronDown,
    Up: BsChevronUp,
    Volume: BsFillVolumeUpFill,
    Previous: BsArrowCounterclockwise,
    Stop: BsFillStopCircleFill,
}
